### ISSUE TITLE
Broken since last version: `type object 'UniqueIdVersion' has no attribute 'V2'`

### ISSUE THREAD

**Issue by folke** [Breina/PowerTagGateway#28]
**Describe the bug**

**Versions**
 - HomeAssistant: latest
 - Integration: latest

**Logs**
- [ ] Attached logs to this issue

```
2024-11-13 11:24:25.757 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up powertag_gateway platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/powertag_gateway/sensor.py", line 79, in async_setup_entry
    entities = setup_entities(hass, config_entry, sensors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/powertag_gateway/entity_base.py", line 251, in setup_entities
    collect_entities(
  File "/config/custom_components/powertag_gateway/entity_base.py", line 186, in collect_entities
    entities.append(powertag_entity(*args))
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/powertag_gateway/sensor.py", line 113, in __init__
    super().__init__(client, modbus_index, tag_device, "total active energy", unique_id_version)
  File "/config/custom_components/powertag_gateway/entity_base.py", line 131, in __init__
    if unique_id_version == UniqueIdVersion.V2:
                            ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UniqueIdVersion' has no attribute 'V2'
```

**Comment by folke** [comment]
There is indeed no v2: https://github.com/Breina/PowerTagGateway/blob/605bedb9804c4719521e48ffaf3d4f3cc38e127b/custom_components/powertag_gateway/__init__.py#L23

**Comment by lattaai8** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added V2 to UniqueIdVersion enum and updated the code to handle the new version. This fixes the AttributeError and ensures backward compatibility.

You can review changes in this commit: https://github.com/lattaai8/Breina-PowerTagGateway-28/commit/04bc917aca8fd82145c39836a2e38b800b628af2.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Breina** [comment]
Shit sorry

**Comment by Breina** [comment]
I deleted the latest release, that was trash on my part.

**Comment by folke** [comment]
v0.5.3 also references `V2`.

Last working version is `v0.5.2`

**Comment by Breina** [comment]
Ok should be good now. :(
