### ISSUE TITLE
Does not work after HA Core upgrade 2024.12.0

### ISSUE THREAD

**Issue by kelddamsbo** [Breina/PowerTagGateway#30]
**Describe the bug**
Integration will not start up

**Versions**
 - HomeAssistant: [e.g. 2024.12.0]
 - Integration: v1.5.0

**Logs**
Logger: homeassistant.config_entries
Kilde: config_entries.py:640
Første forekomst: 4. december 2024 kl. 21.08.26 (2 forekomster)
Senest logget: 07.31.48

Error setting up entry pas600 for powertag_gateway
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1271, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1303, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/powertag_gateway/binary_sensor.py", line 11, in <module>
    from .device_features import FeatureClass
  File "/config/custom_components/powertag_gateway/device_features.py", line 7, in <module>
    class FeatureClass(Enum):
    ...<15 lines>...
        CO2 = auto()
  File "/config/custom_components/powertag_gateway/device_features.py", line 22, in FeatureClass
    TEMP1 = auto()
    ^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 431, in __setitem__
    v.value = self._generate_next_value(
              ~~~~~~~~~~~~~~~~~~~~~~~~~^
            key, 1, len(self._member_names), self._last_values[:],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            )
            ^
  File "/usr/local/lib/python3.13/enum.py", line 1248, in _generate_next_value_
    raise TypeError('unable to sort non-numeric values') from None
TypeError: unable to sort non-numeric values

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/powertag_gateway/__init__.py", line 57, in async_setup_entry
    await hass.config_entries.async_forward_entry_setup(entry, platform)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2349, in async_forward_entry_setup
    result = await self._async_forward_entry_setup(entry, domain, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2380, in _async_forward_entry_setup
    await integration.async_get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1107, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1172, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1097, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1291, in _load_platform
    raise ImportError(
        f"Exception importing {self.pkg_path}.{platform_name}"
    ) from err
ImportError: Exception importing custom_components.powertag_gateway.binary_sensor

**Comment by folke** [comment]
The integration now loads, but the devices still show up as unavailable. Will see what else might be wrong

**Comment by JosefNoll** [comment]
Need help, @kelddamsbo or @folke - looks like I'm to stupid to find the 3 dots for deleting and re-installing the PowerTag Link Gateway in HACS. Running from Vivaldi on MacOS (though can't find the remove in the app either).
How can I update the PowerTag Link Gateway?
